name: Hello

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name to print"
        required: true
        default: "World"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ inputs.name }}!"
      - uses: actions/checkout@v4
